import { useEffect, useMemo, useRef, useState } from 'react'
import type { Session } from '@supabase/supabase-js'
import type { Trade, TradeForm } from '../../types/trade'
import type { TradeScreenshot } from '../../types/screenshot'
import { calculateFromForm, numberOrNull } from '../../utils/tradeCalculations'
import { createTrade, updateTrade } from '../../services/tradeService'
import { ALLOWED_SCREENSHOT_TYPES, deleteTradeScreenshot, listTradeScreenshots, MAX_SCREENSHOTS_PER_TRADE, MAX_SCREENSHOT_SIZE, uploadTradeScreenshots } from '../../services/screenshotService'
import { money, toLocalInput } from '../../utils/formatters'
import { Icon } from '../../components/icons/Icon'

const emptyForm=():TradeForm=>({trade_date:new Date(Date.now()-new Date().getTimezoneOffset()*60000).toISOString().slice(0,16),instrument:'',direction:'Long',entry_price:'',stop_loss:'',take_profit:'',exit_price:'',position_size:'',commission:'0',setup:'',notes:''})
const fromTrade=(t:Trade):TradeForm=>({trade_date:toLocalInput(t.trade_date),instrument:t.instrument,direction:t.direction,entry_price:t.entry_price?.toString()??'',stop_loss:t.stop_loss?.toString()??'',take_profit:t.take_profit?.toString()??'',exit_price:t.exit_price?.toString()??'',position_size:t.position_size?.toString()??'',commission:(t.commission??0).toString(),setup:t.setup??'',notes:t.notes??''})

export function TradeModal({session,trade,onClose,onSaved}:{session:Session;trade:Trade|null;onClose:()=>void;onSaved:()=>Promise<void>}){
 const[form,setForm]=useState<TradeForm>(()=>trade?fromTrade(trade):emptyForm()),[saving,setSaving]=useState(false),[error,setError]=useState(''),[screenshots,setScreenshots]=useState<TradeScreenshot[]>([]),[pending,setPending]=useState<File[]>([]),[dragging,setDragging]=useState(false),[persistedId,setPersistedId]=useState<string|null>(trade?.id??null)
 const inputRef=useRef<HTMLInputElement>(null),calc=useMemo(()=>calculateFromForm(form),[form]);const field=(k:keyof TradeForm,v:string)=>setForm(c=>({...c,[k]:v}))
 useEffect(()=>{if(!trade)return;listTradeScreenshots(trade.id).then(setScreenshots).catch(()=>setError('Screenshots konden niet worden geladen. Voer indien nodig de v4.1 SQL-migratie uit.'))},[trade])
 const addFiles=(files:File[])=>{setError('');const valid=files.filter(f=>ALLOWED_SCREENSHOT_TYPES.includes(f.type)&&f.size<=MAX_SCREENSHOT_SIZE);if(valid.length!==files.length)setError('Alleen PNG, JPG/JPEG of WEBP tot 5 MB per bestand zijn toegestaan.');const room=Math.max(0,MAX_SCREENSHOTS_PER_TRADE-screenshots.length-pending.length);setPending(p=>[...p,...valid.slice(0,room)]);if(valid.length>room)setError(`Maximaal ${MAX_SCREENSHOTS_PER_TRADE} screenshots per trade.`)}
 const removeExisting=async(item:TradeScreenshot)=>{if(!confirm('Screenshot verwijderen?'))return;try{await deleteTradeScreenshot(item);setScreenshots(s=>s.filter(x=>x.id!==item.id))}catch(e){setError(e instanceof Error?e.message:'Screenshot verwijderen mislukt')}}
 const save=async(e:React.FormEvent)=>{e.preventDefault();if(calc.pnl===null){setError('Vul Entry, Exit en Positiegrootte in om P&L automatisch te berekenen.');return}setSaving(true);setError('');const payload={user_id:session.user.id,trade_date:new Date(form.trade_date).toISOString(),instrument:form.instrument.trim().toUpperCase(),direction:form.direction,entry_price:numberOrNull(form.entry_price),stop_loss:numberOrNull(form.stop_loss),take_profit:numberOrNull(form.take_profit),exit_price:numberOrNull(form.exit_price),position_size:numberOrNull(form.position_size),commission:Number(form.commission||0),pnl:calc.pnl,r_multiple:calc.rMultiple,setup:form.setup.trim()||null,notes:form.notes.trim()||null};try{let saved:Trade;if(persistedId){saved=await updateTrade(persistedId,payload)}else{saved=await createTrade(payload as Omit<Trade,'id'|'created_at'>);setPersistedId(saved.id)}if(pending.length){const uploaded=await uploadTradeScreenshots(session.user.id,saved.id,pending);setScreenshots(s=>[...s,...uploaded]);setPending([])}await onSaved();onClose()}catch(e){setError(e instanceof Error?e.message:'Opslaan mislukt')}finally{setSaving(false)}}
 return <div className="modal-backdrop" onMouseDown={e=>e.target===e.currentTarget&&onClose()}><section className="modal"><div className="modal-header"><div><p className="eyebrow">JOURNAL</p><h2>{trade?'Trade bewerken':'Trade toevoegen'}</h2></div><button className="close-button" onClick={onClose}>×</button></div><form onSubmit={save}><div className="form-grid"><div><label>Datum & tijd</label><input type="datetime-local" value={form.trade_date} onChange={e=>field('trade_date',e.target.value)} required/></div><div><label>Instrument *</label><input value={form.instrument} onChange={e=>field('instrument',e.target.value)} placeholder="NQ, EURUSD, BTC" required/></div><div><label>Richting</label><select value={form.direction} onChange={e=>field('direction',e.target.value)}><option>Long</option><option>Short</option></select></div><div><label>Positiegrootte *</label><input type="number" step="any" value={form.position_size} onChange={e=>field('position_size',e.target.value)} placeholder="Aantal / multiplier" required/></div><div><label>Entry *</label><input type="number" step="any" value={form.entry_price} onChange={e=>field('entry_price',e.target.value)} required/></div><div><label>Exit *</label><input type="number" step="any" value={form.exit_price} onChange={e=>field('exit_price',e.target.value)} required/></div><div><label>Stop loss</label><input type="number" step="any" value={form.stop_loss} onChange={e=>field('stop_loss',e.target.value)}/></div><div><label>Take profit</label><input type="number" step="any" value={form.take_profit} onChange={e=>field('take_profit',e.target.value)}/></div><div><label>Commissie / fees (€)</label><input type="number" min="0" step="any" value={form.commission} onChange={e=>field('commission',e.target.value)}/></div><div><label>Setup / strategie</label><input value={form.setup} onChange={e=>field('setup',e.target.value)} placeholder="Breakout, FVG..."/></div><div className="span-2"><label>Notities</label><textarea rows={4} value={form.notes} onChange={e=>field('notes',e.target.value)} placeholder="Wat ging goed? Wat kon beter?"/></div></div>
 <div className="screenshot-section"><div className="section-heading"><div><label>Trade screenshots</label><small>PNG, JPG/JPEG of WEBP · max. 5 MB · maximaal 5</small></div><Icon name="image"/></div><div className={`drop-zone ${dragging?'dragging':''}`} onDragOver={e=>{e.preventDefault();setDragging(true)}} onDragLeave={()=>setDragging(false)} onDrop={e=>{e.preventDefault();setDragging(false);addFiles(Array.from(e.dataTransfer.files))}} onClick={()=>inputRef.current?.click()}><Icon name="upload" size={24}/><strong>Sleep screenshots hierheen</strong><span>of klik om bestanden te selecteren</span><input ref={inputRef} type="file" hidden multiple accept="image/png,image/jpeg,image/webp" onChange={e=>{addFiles(e.target.files ? Array.from(e.target.files) : []);e.currentTarget.value=''}}/></div>{(screenshots.length>0||pending.length>0)&&<div className="screenshot-grid">{screenshots.map(item=><div className="screenshot-thumb" key={item.id}>{item.url?<img src={item.url} alt={item.file_name}/>:<div className="image-placeholder"><Icon name="image"/></div>}<div className="screenshot-meta"><span title={item.file_name}>{item.file_name}</span><button type="button" aria-label="Screenshot verwijderen" onClick={()=>removeExisting(item)}><Icon name="trash" size={15}/></button></div></div>)}{pending.map((file,i)=><PendingPreview key={`${file.name}-${i}`} file={file} onRemove={()=>setPending(p=>p.filter((_,x)=>x!==i))}/>)}</div>}</div>
 <div className="calculation-preview"><div><span>Bruto P&L</span><strong>{calc.grossPnl===null?'—':money(calc.grossPnl)}</strong></div><div><span>Netto P&L</span><strong className={(calc.pnl??0)>=0?'positive':'negative'}>{calc.pnl===null?'—':money(calc.pnl)}</strong></div><div><span>R-multiple</span><strong>{calc.rMultiple===null?'—':`${calc.rMultiple.toFixed(2)}R`}</strong></div></div>{error&&<div className="error-banner">{error}</div>}<div className="modal-actions"><button type="button" className="cancel-button" onClick={onClose}>Annuleren</button><button type="submit" className="add-trade-button" disabled={saving}><Icon name="save" size={16}/>{saving?'Opslaan...':trade?'Wijzigingen opslaan':'Trade opslaan'}</button></div></form></section></div>}

function PendingPreview({file,onRemove}:{file:File;onRemove:()=>void}){const[url,setUrl]=useState('');useEffect(()=>{const object=URL.createObjectURL(file);setUrl(object);return()=>URL.revokeObjectURL(object)},[file]);return <div className="screenshot-thumb pending">{url&&<img src={url} alt={file.name}/>}<div className="screenshot-meta"><span title={file.name}>{file.name}</span><button type="button" aria-label="Screenshot verwijderen" onClick={onRemove}><Icon name="trash" size={15}/></button></div><em>Nog niet geüpload</em></div>}
