import { useMemo, useState } from 'react'
import type { Session } from '@supabase/supabase-js'
import type { Trade, TradeForm } from '../../types/trade'
import { calculateFromForm, numberOrNull } from '../../utils/tradeCalculations'
import { createTrade, updateTrade } from '../../services/tradeService'
import { money, toLocalInput } from '../../utils/formatters'

const emptyForm=():TradeForm=>({trade_date:new Date(Date.now()-new Date().getTimezoneOffset()*60000).toISOString().slice(0,16),instrument:'',direction:'Long',entry_price:'',stop_loss:'',take_profit:'',exit_price:'',position_size:'',commission:'0',setup:'',notes:''})
const fromTrade=(t:Trade):TradeForm=>({trade_date:toLocalInput(t.trade_date),instrument:t.instrument,direction:t.direction,entry_price:t.entry_price?.toString()??'',stop_loss:t.stop_loss?.toString()??'',take_profit:t.take_profit?.toString()??'',exit_price:t.exit_price?.toString()??'',position_size:t.position_size?.toString()??'',commission:(t.commission??0).toString(),setup:t.setup??'',notes:t.notes??''})
export function TradeModal({session,trade,onClose,onSaved}:{session:Session;trade:Trade|null;onClose:()=>void;onSaved:()=>Promise<void>}){const[form,setForm]=useState<TradeForm>(()=>trade?fromTrade(trade):emptyForm()),[saving,setSaving]=useState(false),[error,setError]=useState('');const calc=useMemo(()=>calculateFromForm(form),[form]);const field=(k:keyof TradeForm,v:string)=>setForm(c=>({...c,[k]:v}))
 const save=async(e:React.FormEvent)=>{e.preventDefault();if(calc.pnl===null){setError('Vul Entry, Exit en Positiegrootte in om P&L automatisch te berekenen.');return}setSaving(true);setError('');const payload={user_id:session.user.id,trade_date:new Date(form.trade_date).toISOString(),instrument:form.instrument.trim().toUpperCase(),direction:form.direction,entry_price:numberOrNull(form.entry_price),stop_loss:numberOrNull(form.stop_loss),take_profit:numberOrNull(form.take_profit),exit_price:numberOrNull(form.exit_price),position_size:numberOrNull(form.position_size),commission:Number(form.commission||0),pnl:calc.pnl,r_multiple:calc.rMultiple,setup:form.setup.trim()||null,notes:form.notes.trim()||null};try{trade?await updateTrade(trade.id,payload):await createTrade(payload as Omit<Trade,'id'|'created_at'>);await onSaved();onClose()}catch(e){setError(e instanceof Error?e.message:'Opslaan mislukt')}finally{setSaving(false)}}
 return <div className="modal-backdrop" onMouseDown={e=>e.target===e.currentTarget&&onClose()}><section className="modal"><div className="modal-header"><div><p className="eyebrow">JOURNAL</p><h2>{trade?'Trade bewerken':'Trade toevoegen'}</h2></div><button className="close-button" onClick={onClose}>×</button></div><form onSubmit={save}><div className="form-grid"><div><label>Datum & tijd</label><input type="datetime-local" value={form.trade_date} onChange={e=>field('trade_date',e.target.value)} required/></div><div><label>Instrument *</label><input value={form.instrument} onChange={e=>field('instrument',e.target.value)} placeholder="NQ, EURUSD, BTC" required/></div><div><label>Richting</label><select value={form.direction} onChange={e=>field('direction',e.target.value)}><option>Long</option><option>Short</option></select></div><div><label>Positiegrootte *</label><input type="number" step="any" value={form.position_size} onChange={e=>field('position_size',e.target.value)} placeholder="Aantal / multiplier" required/></div><div><label>Entry *</label><input type="number" step="any" value={form.entry_price} onChange={e=>field('entry_price',e.target.value)} required/></div><div><label>Exit *</label><input type="number" step="any" value={form.exit_price} onChange={e=>field('exit_price',e.target.value)} required/></div><div><label>Stop loss</label><input type="number" step="any" value={form.stop_loss} onChange={e=>field('stop_loss',e.target.value)}/></div><div><label>Take profit</label><input type="number" step="any" value={form.take_profit} onChange={e=>field('take_profit',e.target.value)}/></div><div><label>Commissie / fees (€)</label><input type="number" min="0" step="any" value={form.commission} onChange={e=>field('commission',e.target.value)}/></div><div><label>Setup / strategie</label><input value={form.setup} onChange={e=>field('setup',e.target.value)} placeholder="Breakout, FVG..."/></div><div className="span-2"><label>Notities</label><textarea rows={4} value={form.notes} onChange={e=>field('notes',e.target.value)} placeholder="Wat ging goed? Wat kon beter?"/></div></div><div className="calculation-preview"><div><span>Bruto P&L</span><strong>{calc.grossPnl===null?'—':money(calc.grossPnl)}</strong></div><div><span>Netto P&L</span><strong className={(calc.pnl??0)>=0?'positive':'negative'}>{calc.pnl===null?'—':money(calc.pnl)}</strong></div><div><span>R-multiple</span><strong>{calc.rMultiple===null?'—':`${calc.rMultiple.toFixed(2)}R`}</strong></div></div>{error&&<div className="error-banner">{error}</div>}<div className="modal-actions"><button type="button" className="cancel-button" onClick={onClose}>Annuleren</button><button type="submit" className="add-trade-button" disabled={saving}>{saving?'Opslaan...':trade?'Wijzigingen opslaan':'Trade opslaan'}</button></div></form></section></div>}
