import { useEffect, useState, type FormEvent } from 'react'
import type { TradingPlanCategory, TradingPlanRule, TradingPlanRuleInput } from '../../../types/tradingPlan'

const labels: Record<TradingPlanCategory, string> = { bias: 'Bias', poi: 'POI', entry: 'Entry', exit: 'Exit' }

export function RuleModal({ category, rule, onClose, onSave }: { category: TradingPlanCategory; rule: TradingPlanRule | null; onClose: () => void; onSave: (input: TradingPlanRuleInput) => Promise<void> }) {
  const [title, setTitle] = useState(''), [description, setDescription] = useState(''), [enabled, setEnabled] = useState(true), [saving, setSaving] = useState(false), [error, setError] = useState('')
  useEffect(() => { setTitle(rule?.title ?? ''); setDescription(rule?.description ?? ''); setEnabled(rule?.enabled ?? true) }, [rule])
  const submit = async (event: FormEvent) => { event.preventDefault(); if (!title.trim()) return; setSaving(true); setError(''); try { await onSave({ category, title: title.trim(), description: description.trim(), enabled }); onClose() } catch { setError('Opslaan mislukt. Probeer het opnieuw.') } finally { setSaving(false) } }
  return <div className="modal-backdrop" onMouseDown={event => event.target === event.currentTarget && onClose()}><form className="modal rule-modal" onSubmit={submit}><div className="modal-header"><div><p className="eyebrow">{labels[category].toUpperCase()} PLAN</p><h2>{rule ? 'Regel bewerken' : 'Nieuwe regel'}</h2></div><button type="button" className="close-button" onClick={onClose}>×</button></div><label>Titel</label><input autoFocus value={title} onChange={e => setTitle(e.target.value)} placeholder="Bijv. Alleen traden met duidelijke HTF bias"/><label>Toelichting <span className="optional">optioneel</span></label><textarea rows={4} value={description} onChange={e => setDescription(e.target.value)} placeholder="Beschrijf wanneer deze regel wel of niet geldt..."/><label className="toggle-row"><input type="checkbox" checked={enabled} onChange={e => setEnabled(e.target.checked)}/><span><strong>Regel actief</strong><small>Actieve regels tellen mee voor je tradingplan.</small></span></label>{error&&<div className="error-banner compact">{error}</div>}<div className="modal-actions"><button type="button" className="cancel-button" onClick={onClose}>Annuleren</button><button className="add-trade-button" disabled={saving || !title.trim()}>{saving ? 'Opslaan...' : 'Regel opslaan'}</button></div></form></div>
}
